Add sex symbol to audio sources list
jamesnicolas/yomichan-forvo-server pull request #7
Opened 2022-03-15 21:51 UTC by MarvNC

It adds a biological sex symbol to the text that is displayed. If you think the string might look better by rearranging things that would be fine.

2022-06-21 08:17 UTC, cyphar requested changes

2022-06-21 08:17 UTC, cyphar commented on __init__.py
> +            genderSymbol = genderSymbol if genderSymbol is not None else ''
```suggestion
            genderSymbol = genderSymbols.get(gender, "")
```

2022-06-21 08:17 UTC, cyphar commented on __init__.py
> +            gender = gender.group(1).strip() if gender is not None else ''
```suggestion
            gender = re.search(r"\((Male|Female)",i.get_text(strip=True)).group(1).strip()
```

2022-06-21 08:17 UTC, cyphar commented on __init__.py
> +    server_thread.start()
No need to remove the last newline.

2022-06-21 16:27 UTC, MarvNC commented
Thank you @cyphar!

2022-09-04 22:11 UTC, jamesnicolas commented
Going to merge this and make some config changes before deploying

2022-09-04 22:11 UTC, merged

2022-10-22 13:03 UTC, cyphar commented on __init__.py
> +            gender = gender.group(1).strip() if gender is not None else ''
My bad, this was actually wrong to suggest. Fixed in #12.